version: '2'
services:
  product-server:
    build: .
    volumes:
      - ./pki/keystore:/etc/ssl/certs/
      - ./pki/truststore:/etc/ssl/trust/
  nginx-product:
    build: nginx
    volumes:
      - ./pki/keystore:/etc/ssl/certs/
      - ./pki/truststore:/etc/ssl/trust/
    ports:
      - 8080:443
      - 8088:80
    depends_on:
      - product-server
  hospital-server:
    build: ../hospital_platform
    volumes:
      - ../hospital_platform/ssl/keystore:/etc/ssl/certs/
      - ../hospital_platform/ssl/truststore:/etc/ssl/trust/
      - ../hospital_platform/ssl/ocsp:/etc/ssl/ocsp/
      - ../logger/:/etc/logger/
      - ../hospital_logger_configs/:/etc/logger_configs/
    restart: always
    depends_on:
      - couchbase-server
  nginx-hospital:
    build: ../hospital_platform/nginx
    volumes:
      - ../hospital_platform/ssl/keystore:/etc/ssl/certs/
      - ../hospital_platform/ssl/truststore:/etc/ssl/trust/
      - ../hospital_platform/ssl/ocsp:/etc/ssl/ocsp/
    ports:
      - 8081:443
      - 7081:442
    depends_on:
      - hospital-server
  couchbase-server:
    build: ../hospital_platform/couchbase
    ports:
      - 8000:8091
    volumes:
      - couchbase:/opt/couchbase/var
  mail-server:
    image: 'schickling/mailcatcher'
    ports:
    - 1025:1025
    - 1080:1080
volumes:
  couchbase: