package com.admin.platform.privileges;

public enum Privilege {
    READ_DEVICES_PRIVILEGE,
    WRITE_DEVICES_PRIVILEGE,
    CREATE_CSR_PRIVILEGE,
    CHANGE_TOKEN_STATUS_PRIVILEGE,
    READ_TOKEN_STATUS_PRIVILEGE
}
